AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  ApiEndpointFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      Environment:
        Variables:
          TOPIC_ARN: !Ref ApiEndpointTopic
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - sns:Publish
              Resource: !Ref ApiEndpointTopic
      Events:
        ApiEndpointApi:
          Type: Api
          Properties:
            Path: /hello-world
            Method: ANY
  ApiEndpointTopic: 
    Type: AWS::SNS::Topic