AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Parameters: 
  CloudWatchNameSpace: 
    Type: String
    Default: Desole
    Description: Namespace for CloudWatch Metrics 
  PinpointApplicationId: 
    Type: String
    Description: Pinpoint (Mobile Hub) Application ID. Leave blank if you do not want to log events to Pinpoint analytics
  PinpointEventName:
    Type: String
    Default: Error
    Description: The name for custom events logged to Pinpoint analytics 
Resources:
  CollectorApi:
    Type: AWS::Serverless::Function
    Properties:
      Handler: collector-api.handler
      Runtime: nodejs8.10
      Environment:
        Variables:
          TOPIC_ARN: !Ref CollectorTopic
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - sns:Publish
              Resource: !Ref CollectorTopic
      Events:
        ApiEndpointApi:
          Type: Api
          Properties:
            Path: /hello-world
            Method: ANY
  CollectorTopic: 
    Type: AWS::SNS::Topic
  S3Publisher:
    Type: AWS::Serverless::Function
    Properties:
      Handler: s3-publisher.handler
      Runtime: nodejs8.10
      Environment:
        Variables:
          BUCKET_NAME: !Ref CollectedEventsStorage
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: 's3:PutObject'
              Resource: !Sub 'arn:aws:s3:::${CollectedEventsStorage}/*'
      Events:
        CollectorSubscribedTopic:
          Type: SNS
          Properties:
            Topic: !Ref CollectorTopic
  CloudwatchPublisher:
    Type: AWS::Serverless::Function
    Properties:
      Handler: cloudwatch-publisher.handler
      Runtime: nodejs8.10
      Environment:
        Variables:
          CLOUDWATCH_NAMESPACE: !Ref CloudWatchNameSpace
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: 'cloudwatch:PutMetricData'
              Resource: '*'
      Events:
        CollectorSubscribedTopic:
          Type: SNS
          Properties:
            Topic: !Ref CollectorTopic
  PinpointPublisher:
    Type: AWS::Serverless::Function
    Properties:
      Handler: pinpoint-publisher.handler
      Runtime: nodejs8.10
      Environment:
        Variables:
          MOBILE_HUB_APPLICATION: !Ref PinpointApplicationId
          EVENT_NAME: !Ref PinpointEventName
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: 'mobileanalytics:PutEvents'
              Resource: '*'
      Events:
        CollectorSubscribedTopic:
          Type: SNS
          Properties:
            Topic: !Ref CollectorTopic
  CollectedEventsStorage:
    Type: AWS::S3::Bucket
