AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  CollectorPublisherFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: collector-api.handler
      Runtime: nodejs8.10
      Environment:
        Variables:
          TOPIC_ARN: !Ref CollectorTopic
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - sns:Publish
              Resource: !Ref CollectorTopic
      Events:
        ApiEndpointApi:
          Type: Api
          Properties:
            Path: /hello-world
            Method: ANY
  CollectorTopic: 
    Type: AWS::SNS::Topic
  CollectorSubscriberFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: s3-publisher.handler
      Runtime: nodejs8.10
      Environment:
        Variables:
          BUCKET_NAME: !Ref CollectedEventsStorage
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: 's3:PutObject'
              Resource: !Sub 'arn:aws:s3:::${CollectedEventsStorage}/*'
      Events:
        CollectorSubscribedTopic:
          Type: SNS
          Properties:
            Topic: !Ref CollectorTopic
  CollectedEventsStorage:
    Type: AWS::S3::Bucket
